config/routes.rb
TourPlanner::Application.routes.draw do
  root to: 'users#show'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'facebook_login', to: 'sessions#facebook_login'
  get 'facebook_finalize', to: 'sessions#facebook_finalize'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update] do
    resources :member_requests, only: [:index]
    resources :notifications, only: [:index]
    put 'change_password', to: 'passwords#update'
  end
  
  resources :bands, only: [:create, :destroy, :show, :new, :index, :edit, :update] do
    resources :events, only: [:create, :destroy, :edit, :update, :new, :index]
    resources :tours, only: [:new, :create, :edit]
    resources :member_requests, only: [:create]
    post 'grab_shows', to: "events#grab_shows", as: "grab_shows"
    put 'grab_image', to: "bands#grab_image", as: "grab_image"
    get 'map_embed_data', to: "bands#map_embed_data"
  end
  
  put "member_requests/:id/deny_request", to: 'member_requests#deny', as: "deny_request"
  put "band_memberships/:id/make_admin", to: 'band_memberships#make_admin', as: "make_admin"
  
  post 'search', to: 'bands#search', as: 'band_search'
  
  resources :band_memberships, only: [:create, :destroy]
  
  resources :events, only: [:destroy, :index, :show]
  
  resources :venues, only: [:index, :show]
  
  resources :tours, only: [:show, :destroy, :update] do
    member do 
      get 'map_embed_data', to: "tours#map_embed_data"
      get 'distance', to: "tours#distance"
      put 'events/:event_id', to: "tours#remove_event", as: "remove_event"
    end
  end
  
  resources :notifications, only: [:destroy]
  
  namespace :demo do
    get 'one'
    get 'new_band'
    get 'band_page'
    get 'band_image'
    get 'shows_grabbed'
    get 'notifications'
    get 'admins'
    get 'band_tour'
  end
end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  layout 'demo/demo_layout'
  include ToursHelper
  include DemoHelper  
    
  def one
    session[:demo_band] = params[:choice]
    demo_setup
    
    case session[:demo_band]
    when "Beyonce"
      story = "She asked you to be the tour manager for her upcoming European tour!"
    when "The Rolling Stones"
      story = "They want you to be the tour manager for their upcoming Australian tour!"
    when "Dr. Dog"
      story = "They need you to be the tour manager for their upcoming tour of the U.S!"
    when "One Direction"
      story = "They begged you to be the tour manager for their upcoming World Tour!"
    end
    
    flash[:demo] = 
    ["Congratulations! You were recently contacted by <strong>#{@band.name}</strong>! <br><br>
      (you can quit this demo at any time by clicking 'Log Out') ".html_safe,
     story,
     "You want to be on top of your game, so you signed up for <strong>Tour Planner</strong>.".html_safe,
     "The first thing you need to do is add <strong>#{@band.name}</strong> as one of your bands".html_safe,
     "<h2>Click on the <strong>'Add Band'</strong> button at the bottom of the page to continue.</h2>".html_safe]
     
    render 'demo/user_show'
  end
  
  def new_band
    demo_setup
    
    flash[:demo] = 
    ["You can add and manage as many bands as you want.", 
     "It's easy to add a new band. <br>
      We filled out the form for you.", 
     "Just click <strong> Create Band </strong> to move on.".html_safe]
  end
  
  def band_page
    demo_setup
    
    flash[:demo] = 
    ["You created a band page!".html_safe,
      "Let's spice it up a bit by adding a photo.",
      "You can upload a photo on your own, but we make it super simple <br>
      with the <strong> Grab Image </strong> button.".html_safe,
      "If you've entered your band name correctly, it will go off into <br>
      the internet and grab a photo (via Seat Geek).", 
      "Try it out! (Click the 'Grab Image' button to continue.)".html_safe]
  end
  
  def band_image
    demo_setup
    
    flash[:demo] = 
    ["Bam! There it is!",
      "The eyes of #{session[:demo_band]} will keep you focused.",
      "You can enter in shows yourself, or you can use some 
      <br> behind the scenes magic to grab existing event data.",
      "Click on the <strong>Grab Shows From Seat Geek</strong> 
      button to populate <br> your page with all the 
      current #{session[:demo_band]} events.".html_safe]
  end
  
  def shows_grabbed
    demo_setup  
    demo_events_setup
    @requests = 1
  
    flash[:demo] = 
    ["Using the <strong> Grab Shows </strong> button automatically creates a tour <br> 
      containing all the shows that were grabbed.".html_safe,
     "Before we look at the tour, it looks like you have a notification! What could it be?",
     "Click on the 'Notifications' up above to take a look.".html_safe]
  end
  
  
  def notifications
    demo_setup
    @requests = 1    
    
    flash[:demo] = 
    ["You received a member request! Someone wants to join <strong> #{@band.name} </strong>.".html_safe,
    "Members of a band will receive notifications <br> when shows and tours are added, updated, or
     deleted.".html_safe,
    "Members are also alerted when someone joins or (gasp!) leaves the band.",
    "Looks like you got a request from <strong> #{@band.name}'s </strong> agent.",
    "She wants to stay up to date.",
    "Click <strong> Accept </strong> to add this band member."]
  end
  
  def admins
    demo_setup
    demo_new_member_setup    
    demo_events_setup
    
    flash[:demo] = 
    ["Once you accept a new member, you have the option of making them an admin.",
    "Admins are allowed to create, edit, and delete a band's shows and tours.",
    "Admins receive notifications when band details are editted.",
    "Since you created this band, you were made an admin by default.",
    "Let's hold off on making <strong> #{session[:demo_band]}'s </strong> agent an admin for now.",
    "Instead, let's take a look at the coolest part of <strong> Tour Planner </strong>... the tours!",
    "Click on <strong> #{session[:demo_band]}'s </strong> tour to check it out."]
  end
  
  def band_tour
    demo_setup
    demo_events_setup
    @geo_data = geo_data_tour(@tour, up_to_date: false, event_links: false, ticket_links: true)
    
    case @band.name
    when "Beyonce"
      @distance = 1297
      quote = "<strong>\"Power's not given to you. You have to take it.\" </strong> ~ Beyonce"
    when "The Rolling Stones"
      @distance =  540
      quote = "<br><strong>\"Lose your dreams and you will lose your mind.<br> 
               Ain't life unkind?\" </strong> ~ The Rolling Stones"
    when "Dr. Dog"
      @distance = 5582
      quote = "<strong><p>\"Do you like things the way they seem? <br> 
               Or are you looking behind the scenes?\" </strong> ~ Dr. Dog</p>"
    when "One Direction"
      @distance = 10623
      quote = "<strong><p>\"I will carry you over fire and water for your love. I will hold <br> 
               you closer, hope your heart is strong enough.\" </strong> ~ One Direction</p>"
    end
    
    flash[:demo] = 
    ["<strong> Tour Planner </strong> auto-generates a 
     map from all the shows within a given tour.".html_safe,
     "There are ticket links to the events embedded in each marker.",
     "<strong> Tour Planner </strong> also provides embeddable code <br>
      so you can include this map on your band's website.".html_safe,
      "If you update
      this tour on <strong> Tour Planner </strong>, the changes <br> will be reflected on your
      website's embedded map!".html_safe,
      "Feel free to look around.",
      "That's all for now. Click <a href='#{root_url}' class='target'> here </a> to sign up -or-
      click 
      
      <form action='#{login_url}' method='post' style='display:inline-block'>
        <input type='hidden' 
      		 name='authenticity_token' 
      		 value='<%= form_authenticity_token %>'>

       <input type='hidden' name='user[email]' value='demo-user@tourplanner.co'>
       <input type='hidden' name='user[password]' value='password'>

        <div class='submit'>	 
        	   <input type='submit' value='here' class='target'>
        </div>
      </form>
      
      to sign in as a demo user!
      <br> #{quote} ".html_safe]
  end
end

app/helpers/demo_helper.rb
module DemoHelper
  def demo_setup
    @band = Band.new({name: session[:demo_band] })
    @band.id = 1
    @requests = 0
    @user = User.new({
      email: "you@example.com", 
      password: "password",
    })  
    @user.id = 0
    @current_user = @user
    session[:token] = "demo"
    @band.members = [@user]
    bm = BandMembership.new
    bm.member = @user
    @band.band_memberships = [bm]
    @events = []
    @image = session[:demo_band].downcase.split(" ").join("") + ".jpg"
    @pending_requests = [1]
    @email = "BigShotAgent@AgentsRUs.com"
  end
  
  def demo_events_setup
    file = session[:demo_band].downcase.split(" ").join("") + ".json"
    file_json = File.read("db/demo_bands_json/" + file)
    events = JSON.parse(file_json)["events"]
    
    @tour = Tour.new({name: session[:demo_band] + " Tour"})
    @tour.id = 0
    
    @events = []
    venues = []
    
    events.each_with_index do |show, i|
      next if @events.count > 15
      
      v_data = show["venue"]
      
      venue = Venue
      .new({
        name: v_data["name"],
        address: v_data["address"],
        city: v_data["city"],
        state: v_data["state"],
        zipcode: v_data["postal_code"],
        lat: v_data["location"]["lat"],
        lon: v_data["location"]["lon"]  
      })
      
      next if venues.index { |v| v.name == venue.name }
      
      venue.id = i
  
      next unless venue.valid?
      venues << venue
  
      event = Event.new({
        date: show["datetime_local"],
        ticket_url: show["url"],
        band_id: @band.id,
        venue_id: venue.id,
        tour_id: @tour.id
      })
      
      event.id = i
      
      @events << event
      
      event.venue = venue  
    end
  
    @tours = [@tour]
    @tour.events = @events
    
    cookies[:demo_tour] = nil
    cookies[:demo_tour] = @events.to_json(only: [:id, :date, :ticket_url])
    cookies[:demo_venues] = nil
    cookies[:demo_venues] = venues.to_json(only: [:id, :lat, :lon, :name])
    params[:band_id] = 0
  end 
  
  def demo_new_member_setup
    @agent = User.new({ email: "BigShotAgent@AgentsRUs.com"})
    @agent.id = 1
    @band.members = [@user, @agent]
    bm = BandMembership.new
    bm.admin = true
    bm.member = @user
    bm2 = BandMembership.new
    bm2.admin = false
    bm2.member = @agent
    @band.band_memberships = [bm,bm2]
  end
  
  def demo_xhr
    
    events = JSON.parse(cookies[:demo_tour])
    venues = JSON.parse(cookies[:demo_venues])
    
    event_objects = []
    venue_objects = []
    
    events.each_with_index do |event, i|
      event_obj = Event.new
      event_obj.id = event["id"]
      event_obj.date = event["date"]
      event_obj.ticket_url = event["ticket_url"]
      
      venue_obj2 = Venue.new
      venue_obj2.id = venues[i]["id"]
      venue_obj2.lat = venues[i]["lat"]
      venue_obj2.lon = venues[i]["lon"]
      venue_obj2.name = venues[i]["name"]
      
      event_obj.venue = venue_obj2
      event_objects << event_obj
      venue_objects << venue_obj2
    end
    
    event_objects.delete_if { |event| event.id.to_i == params["event_id"].to_i}
    
    cookies[:demo_tour] = nil
    cookies[:demo_tour] = event_objects.to_json(only: [:id, :date, :ticket_url])
    cookies[:demo_venues] = nil
    cookies[:demo_venues] = venue_objects.to_json(only: [:id, :lat, :lon, :name])
    
    render partial: 'tours/map', 
           locals: { geo_data: geo_data_events(event_objects, 
                     up_to_date: false, 
                     event_links: false, 
                     ticket_links: true) }, 
           layout: false
  end
end

app/views/demo/_demo_header.html.erb
<header>
	<div class="blackout"></div>
	<nav class="clearfix">
			
		<ul id="left-nav">
			<li class="nav-list-item"> 
				<%= link_to 'My Bands', "#", id: 'manage-link', title: "yuadf" %> | 
			</li>
			
			<li class="nav-list-item"> 
			    <%= link_to 'All Bands', "#"%> 
			</li>
			
		</ul>
		
		
		<ul id="right-nav">	
			<li class="nav-list-item">
				<div style="opacity: 0; 
							background: transparent; 
							float: left; 
							position: relative; 
							right: 0; 
							bottom: 0, display: none" class="header-arrow">
							
					<%= image_tag "demo-arrow.png", height: "20px"%>
				</div>
			</li>
			
			<li class="nav-list-item" id="target"> 
				<%= link_to "Notifications", demo_notifications_url, id: "notifications" %> 
				( <%= @requests %> ) |
			</li>
			
			<li class="nav-list-item"> 
				<%= link_to "Settings", "" %> |
			</li>
			
			<li class="nav-list-item" style="position=relative;"> 
				<%= button_to 'Log Out', logout_url, method: :delete, id: 'logout', style: "z-index:10", class: "target"  %>
				<p id="message" > << Click <strong>Log Out</strong> To Quit Guided Tour</p>
			</li>
			
		</ul>
		
		
	</nav>
</header>

app/views/demo/admins.html.erb
<style>
#demo {
}

#show-heading {
}
</style>



<div id="show-heading" class="clearfix">
	<%= render 'layouts/errors' %>

	<div id="show-image">
	  <%= image_tag @image, class: "header-image", id: "band-show-image" %>
    </div>
	
	<h1> <%= @band.name %> </h1>

	
	<% if true %>
	<div id="change-image">
		<div class="edit">
		<% if false%>
			<%= link_to 'Edit Band', edit_band_url(@band)%> |
			<%= link_to 'Delete Band', band_url(@band), method: :delete %> 
		<% end %>
		</div>
	
		<form id="edit-image" action="" method="get"   enctype="multipart/form-data">
		  <input type="hidden" name="_method" value="put">

		  <div class="input">
		    <label for="band_image">Change Band Image</label>
		    <input id="band_image" name="band[image]" type="file">
		  </div>
  
		  <div class="submit">
		    <input type="submit" value="Update Image">
		  </div>
		</form>
		or 
		
		<form id="edit-image" style="display: inline" action="" method="get"   enctype="multipart/form-data">
		  <input type="hidden" name="_method" value="put">
	
		  <input type="hidden" 
				 name="authenticity_token" 
				 value="<%= form_authenticity_token %>">

		  <div class="submit">
		    <input type="submit" value="Grab Image">
		  </div>
		</form>
</div>
	<% end %>
	
	<h3> Members </h3>
	<ul id="members-list">
    <%= button_to "Leave Band" %>

	<% @band.band_memberships.each do |membership| %>
	  <li class="member-list-item">
		  <a href="">
		  <%= membership.member.email %> 
	  
		  <% if membership.role %>
			  - <%= membership.role %>
		  <% end %>
	  
		  <% if true %>
			  <%= membership.admin ? "(Admin)" : "" %>
		  <% end %>
		  </a>
	  
		  <% if !membership.admin %>
			  <%= button_to "Make Admin", "", method: :put %>
		  <% end %>
	  </li>
	<% end %>
	</ul>

</div>

<% if @band.events.count > 0 %>
	<a href="<%= band_events_url(@band) %>">
		<div class="all-shows-box">
			<h2> All <%= @band.name + "'s" %> Shows </h2>
		</div>
	</a>
<% end %> 



<ul id="all-tours">
	<% @tours.each do |tour| %>
	<h1> Tours </h1>
	<li id="tour-block">
		<ul class="block-header target">
			<li class="block-header-item" class="target"> 
				<%= link_to tour.name, demo_band_tour_url, class: "target"%>
			</li>
	    </ul>
		
		<ul id="block-details">

			<% if false%>
				<li class="block-detail"> 
					<%= link_to 'delete', tour_url(tour), method: :delete %>
				</li>
			<% end %>
		</ul>
	</li>
	
	<% end %>
</ul>

<% if true %>
	<a href="">
		<div class="add-box">
			<h2> + Create a Tour </h2>
		</div>
	</a>
<% end %>

<div style="float: right; position:relative; right: 920px; bottom: 180px" id="arrow">
	<%= image_tag "demo-arrow.jpg", width: "100px"%>
</div>

<p>
<h2 style=""> Events (<%= @events.count %>) </h2>
</p>
<% if true%>

<% end %>

<ul id="all-shows">
	<% @events.each do |event| %>

	<li id="show-block">
		<ul class="block-header">
			<% unless true # band name doesn't appear on user page%>
			  <li class="block-header-item"> 
				  <%= link_to event.band.name, "" if event.band %> 
			  </li>
			<% end %>
		<a href="">
			<li class="block-header-item"> 
				<%= l event.date, format: "%d %B %Y"%> 
				<% unless !event.name || event.name.empty? %>
					- <%= event.name %>
				<% end %>
			</li>
		</a>
	    </ul>
	    
		
		<hr>
		
		<ul id="block-details">
			<li class="block-detail"> 
				<a href="">
				  <%= event.venue.name %> 
				</a>
			</li>
			<li class="block-detail"> <%= event.venue.address %> </li>
			<li class="block-detail"> <%= event.venue.city %>, <%= event.venue.state %>  </li>
			<li class="block-detail"> <%= event.venue.zipcode %> </li>
			
			
			<% if false %>
				<li class="block-detail"> 
					<%= link_to 'delete', event_url(event), method: :delete, class: "delete-button" %>
				</li>
			<% end %>
			
		</ul>
	</li>
	
	<% end %>
</ul>

app/views/demo/band_image.html.erb
<div id="show-heading" class="clearfix">
	<%= render 'layouts/errors' %>
	
	<div id="show-image">
	  <%= image_tag @image, class: "header-image", id: "band-show-image"%>
    </div>
	
	<h1> <%= @band.name %> </h1>

	<% if true %>
	<div id="change-image">
		<div class="edit">
		<% if false%>
			<%= link_to 'Edit Band', edit_band_url(@band)%> |
			<%= link_to 'Delete Band', band_url(@band), method: :delete %> 
		<% end %>
		</div>
	
		<form id="edit-image" action="" method="get"   enctype="multipart/form-data">
		  <input type="hidden" name="_method" value="put">

		  <div class="input">
		    <label for="band_image">Change Band Image</label>
		    <input id="band_image" name="band[image]" type="file">
		  </div>
  
		  <div class="submit">
		    <input type="submit" value="Update Image">
		  </div>
		</form>
		or 
		
		<form id="edit-image" style="display: inline" action="<%= demo_band_image_url %>" method="get"   enctype="multipart/form-data">
		  <input type="hidden" name="_method" value="put">
	
		  <input type="hidden" 
				 name="authenticity_token" 
				 value="<%= form_authenticity_token %>">

		  <div class="submit">
		    <input type="submit" value="Grab Image">
		  </div>
		</form>
</div>
	<% end %>
	
	<h3> Members </h3>
	<ul id="members-list">
    <%= button_to "Leave Band" %>
	
	<% @band.band_memberships.each do |membership| %>
	  <li class="member-list-item">
		  <a href="">
		  <%= membership.member.email %> 
	  
		  <% if membership.role %>
			  - <%= membership.role %>
		  <% end %>
	  
		  <% if true %>
		  (Admin)
		  <% end %>
		  </a>
	  
		  <% if false %>
			  <%= button_to "Make Admin", make_admin_url(membership), method: :put %>
		  <% end %>
	  </li>
	<% end %>
	</ul>

</div>

<% if @band.events.count > 0 %>
	<a href="<%= band_events_url(@band) %>">
		<div class="all-shows-box">
			<h2> All <%= @band.name + "'s" %> Shows </h2>
		</div>
	</a>
<% end %>



<% if @band.tours.count > 0 %>
	<h2> Tours (<%= @band.tours.count %>) </h2>
	<%= render 'tours/list', tours: @tours %>
<% end %>

<% if false %>
	<a href="<%= new_band_tour_url(@band) %>">
		<div class="add-box">
			<h2> + Create a Tour </h2>
		</div>
	</a>
<% end %>

<h2> Events (<%= @band.events.count %>) </h2>
<% if true%>

	<%= button_to "Grab Shows From Seat Geek", demo_shows_grabbed_url, method: :get, class: "target" %>

	<a href="<%= %>">
		<div class="add-box">
			<h2> + Add Show </h2>
		</div>
	</a>
<% end %>

<%= render @events, hide_band_name: true %>

<div style="float: left; position: relative; right: 120px; bottom: 150px" id="arrow">
	<%= image_tag "demo-arrow.jpg", width: "100px"%>
</div>

app/views/demo/band_page.html.erb
<div id="show-heading" class="clearfix">
	<%= render 'layouts/errors' %>

	<div id="show-image">
	  <%= image_tag @band.image.url(:thumb), class: "header-image", id: "band-show-image" %>
    </div>
	
	<h1> <%= @band.name %> </h1>

	
	<% if true %>
	<div id="change-image">
		<div class="edit">
		<% if false%>
			<%= link_to 'Edit Band', edit_band_url(@band)%> |
			<%= link_to 'Delete Band', band_url(@band), method: :delete %> 
		<% end %>
		</div>
	
		<form id="edit-image" action="" method="get"   enctype="multipart/form-data">
		  <input type="hidden" name="_method" value="put">

		  <div class="input">
		    <label for="band_image">Change Band Image</label>
		    <input id="band_image" name="band[image]" type="file">
		  </div>
  
		  <div class="submit">
		    <input type="submit" value="Update Image">
		  </div>
		</form>
		or 
		
		<%= button_to "Grab Image", demo_band_image_url, method: :get, class: "target", id: "grab" %>
</div>
	<% end %>
	
	<h3> Members </h3>
	<ul id="members-list">
    <%= button_to "Leave Band" %>

	<% @band.band_memberships.each do |membership| %>
	  <li class="member-list-item">
		  <a href="">
		  <%= membership.member.email %> 
	  
		  <% if membership.role %>
			  - <%= membership.role %>
		  <% end %>
	  
		  <% if true %>
			  <%= membership.member.is_band_admin?(@band) ? "(Admin)" : "" %>
		  <% end %>
		  </a>
	  
		  <% if false %>
			  <%= button_to "Make Admin", make_admin_url(membership), method: :put %>
		  <% end %>
	  </li>
	<% end %>
	</ul>

</div>

<% if @band.events.count > 0 %>
	<a href="<%= band_events_url(@band) %>">
		<div class="all-shows-box">
			<h2> All <%= @band.name + "'s" %> Shows </h2>
		</div>
	</a>
<% end %>



<% if @band.tours.count > 0 %>
	<h2> Tours (<%= @band.tours.count %>) </h2>
	<%= render 'tours/list', tours: @tours %>
<% end %>

<% if false %>
	<a href="<%= new_band_tour_url(@band) %>">
		<div class="add-box">
			<h2> + Create a Tour </h2>
		</div>
	</a>
<% end %>

<h2> Events (<%= @band.events.count %>) </h2>
<% if true%>
	<%= button_to "Grab Shows From Seat Geek", "", method: :get %>

	<a href="<%= %>">
		<div class="add-box">
			<h2> + Add Show </h2>
		</div>
	</a>
<% end %>

<%= render @events, hide_band_name: true %>

<div style="float: left; position: relative; right: 120px; bottom: 424px" id="arrow">
	<%= image_tag "demo-arrow.jpg", width: "100px"%>
</div>

<script>
	$(document).ready(function () {
	
		$("#grab").on("click", function (event) {
			event.preventDefault()
			$("#band-show-image").css("display", "none")
			setTimeout(function () {
				$("#band-show-image").attr("src", "/assets/<%= @image %>")
				$("#band-show-image").css("display", "block")
				setTimeout(function () {
					window.location.href = "<%= demo_band_image_url %>";
				}, 1500)
			}, 2000)
		})
	
	});
</script>

app/views/demo/shows_grabbed.html.erb
<div id="show-heading" class="clearfix">
	<%= render 'layouts/errors' %>

	<div id="show-image">
	  <%= image_tag @image, class: "header-image", id: "band-show-image" %>
    </div>
	
	<h1> <%= @band.name %> </h1>

	
	<% if true %>
	<div id="change-image">
		<div class="edit">
		<% if false%>
			<%= link_to 'Edit Band', edit_band_url(@band)%> |
			<%= link_to 'Delete Band', band_url(@band), method: :delete %> 
		<% end %>
		</div>
	
		<form id="edit-image" action="" method="get"   enctype="multipart/form-data">
		  <input type="hidden" name="_method" value="put">

		  <div class="input">
		    <label for="band_image">Change Band Image</label>
		    <input id="band_image" name="band[image]" type="file">
		  </div>
  
		  <div class="submit">
		    <input type="submit" value="Update Image">
		  </div>
		</form>
		or 
		
		<form id="edit-image" style="display: inline" action="" method="get"   enctype="multipart/form-data">
		  <input type="hidden" name="_method" value="put">
	
		  <input type="hidden" 
				 name="authenticity_token" 
				 value="<%= form_authenticity_token %>">

		  <div class="submit">
		    <input type="submit" value="Grab Image">
		  </div>
		</form>
</div>
	<% end %>
	
	<h3> Members </h3>
	<ul id="members-list">
    <%= button_to "Leave Band" %>

	<% @band.band_memberships.each do |membership| %>
	  <li class="member-list-item">
		  <a href="">
		  <%= membership.member.email %> 
	  
		  <% if membership.role %>
			  - <%= membership.role %>
		  <% end %>
		  (Admin)
		  </a>
	  
		  <% if false %>
			  <%= button_to "Make Admin", make_admin_url(membership), method: :put %>
		  <% end %>
	  </li>
	<% end %>
	</ul>

</div>

<% if @band.events.count > 0 %>
	<a href="<%= band_events_url(@band) %>">
		<div class="all-shows-box">
			<h2> All <%= @band.name + "'s" %> Shows </h2>
		</div>
	</a>
<% end %> 



<ul id="all-tours">
	<% @tours.each do |tour| %>
	<h1> Tours </h1>
	<li id="tour-block">
		<ul class="block-header">
			<li class="block-header-item"> 
				<%= link_to tour.name, demo_band_tour_url%>
			</li>
	    </ul>
		
		<ul id="block-details">

			<% if false%>
				<li class="block-detail"> 
					<%= link_to 'delete', tour_url(tour), method: :delete %>
				</li>
			<% end %>
		</ul>
	</li>
	
	<% end %>
</ul>

<% if true %>
	<a href="">
		<div class="add-box">
			<h2> + Create a Tour </h2>
		</div>
	</a>
<% end %>

<p>
<h2 style=""> Events (<%= @events.count %>) </h2>
</p>
<% if true%>

<% end %>

<ul id="all-shows">
	<% @events.each do |event| %>

	<li id="show-block">
		<ul class="block-header">
			<% unless true # band name doesn't appear on user page%>
			  <li class="block-header-item"> 
				  <%= link_to event.band.name, "" if event.band %> 
			  </li>
			<% end %>
		<a href="">
			<li class="block-header-item"> 
				<%= l event.date, format: "%d %B %Y"%> 
				<% unless !event.name || event.name.empty? %>
					- <%= event.name %>
				<% end %>
			</li>
		</a>
	    </ul>
	    
		
		<hr>
		
		<ul id="block-details">
			<li class="block-detail"> 
				<a href="">
				  <%= event.venue.name %> 
				</a>
			</li>
			<li class="block-detail"> <%= event.venue.address %> </li>
			<li class="block-detail"> <%= event.venue.city %>, <%= event.venue.state %>  </li>
			<li class="block-detail"> <%= event.venue.zipcode %> </li>
			
			
			<% if false %>
				<li class="block-detail"> 
					<%= link_to 'delete', event_url(event), method: :delete, class: "delete-button" %>
				</li>
			<% end %>
			
		</ul>
	</li>
	
	<% end %>
</ul>

<script>
	$('.header-arrow').attr("id", "arrow");
	$('#notifications').addClass('target');
</script>