config/routes.rb
TourPlanner::Application.routes.draw do
  root to: 'users#show'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'facebook_login', to: 'sessions#facebook_login'
  get 'facebook_finalize', to: 'sessions#facebook_finalize'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update] do
    resources :member_requests, only: [:index]
    resources :notifications, only: [:index]
    put 'change_password', to: 'passwords#update'
  end
  
  resources :bands, only: [:create, :destroy, :show, :new, :index, :edit, :update] do
    resources :events, only: [:create, :destroy, :edit, :update, :new, :index]
    resources :tours, only: [:new, :create, :edit]
    resources :member_requests, only: [:create]
    post 'grab_shows', to: "events#grab_shows", as: "grab_shows"
    put 'grab_image', to: "bands#grab_image", as: "grab_image"
    get 'map_embed_data', to: "bands#map_embed_data"
  end
  
  put "member_requests/:id/deny_request", to: 'member_requests#deny', as: "deny_request"
  put "band_memberships/:id/make_admin", to: 'band_memberships#make_admin', as: "make_admin"
  
  post 'search', to: 'bands#search', as: 'band_search'
  
  resources :band_memberships, only: [:create, :destroy]
  
  resources :events, only: [:destroy, :index, :show]
  
  resources :venues, only: [:index, :show]
  
  resources :tours, only: [:show, :destroy, :update] do
    member do 
      get 'map_embed_data', to: "tours#map_embed_data"
      get 'distance', to: "tours#distance"
      put 'events/:event_id', to: "tours#remove_event", as: "remove_event"
    end
  end
  
  resources :notifications, only: [:destroy]
  
  namespace :demo do
    get 'one'
    get 'new_band'
    get 'band_page'
    get 'band_image'
    get 'shows_grabbed'
    get 'notifications'
    get 'admins'
    get 'band_tour'
  end
end

app/models/tour.rb
# == Schema Information
#
# Table name: tours
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  active     :boolean          default(TRUE)
#

class Tour < ActiveRecord::Base
  default_scope where(active: true)
  
  attr_accessible :name, :event_ids, :band_id
  
  validates :name, presence: true
  
  has_many :events, inverse_of: :tour
  
  has_many :notifications, as: :notifiable
  
  def band
    Band.joins(:events)
        .joins(:tours)
        .where("tours.id = ?", self.id)
        .first
  end
  
  def admin_user?(user)
    !BandMembership.where(
      "admin = true AND member_id = ? AND band_id = ?",
       user.id, self.band).empty?
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_filter :require_signed_in!, except: [:map_embed_data, :remove_event]
  
  include ToursHelper
  include DemoHelper
  
  def show
    @tour = Tour.find(params[:id])
    @geo_data = geo_data_tour(@tour)
    @event_remove = true
  end
  
  def new
    @tour = Tour.new
    @band = Band.find(params[:band_id])
  end

  def create
    @tour = Tour.new(params[:tour])
    
    if @tour.save
      notify_tour_create(@tour)
      flash[:success] = ["Tour Created!"]
      redirect_to @tour
    else
      @band = Band.find(params[:band_id])
      flash.now[:errors] = @tour.errors.full_messages
      render :new
    end
  end
  
  def edit
    @tour = Tour.find(params[:id])
    @band = Band.find(params[:band_id])
  end
  
  def update
    @tour = Tour.find(params[:id])
    
    if @tour.update_attributes(params[:tour])
      notify_tour_update(@tour)
      flash[:success] = ["Tour Updated!"]
      redirect_to @tour
    else
      @band = @tour.band
      flash.now[:errors] = @tour.errors.full_messages
      render :edit
    end
  end
  
  def destroy 
    @tour = Tour.find(params[:id])
    band = @tour.band
    if @tour.admin_user?(current_user)
      notify_tour_destroy(@tour)
      @tour.toggle!(:active)
      flash[:success] = ["Tour deleted."]
    end
    redirect_to current_user
  end
  
  def remove_event
    if session[:token] == "demo"
      demo_xhr
    else
      @tour = Tour.find(params[:id])
      @event = Event.find(params[:event_id])
      @event.tour_id = nil
      if @tour.admin_user?(current_user) && @event.save
        if request.xhr?
          render partial: 'tours/map', locals: { geo_data: geo_data_tour(@tour) }, layout: false
        else
          redirect_to(@tour)
        end
      end
    end
  end
  
  def map_embed_data
    allow_outside_access
    render json: 
    geo_data_tour(
      Tour.find(params[:id]), 
      up_to_date: true, 
      event_links: false, 
      ticket_links: true), 
    status: :ok
  end
  
  def distance
    render text: get_distance(Tour.find(params[:id]))
  end
end

app/helpers/tours_helper.rb
module ToursHelper
  include EventsHelper
  
  def geo_data_tour(tour, options = {})
    geo_data_events(tour.events, options)
  end
  
  def get_distance(tour)
      events = tour.events
      origin = events[0]
      origin = origin.venue.lat.to_s + "," + origin.venue.lon.to_s
      destination = events.last
      destination = destination.venue.lat.to_s + "," + destination.venue.lon.to_s
      second_to_last = (events.length > 10) ? 8 : events.length-2
      waypoints = events[1..second_to_last].map { |event| event.venue.lat.to_s + "," + event.venue.lon.to_s }.join("|")
     
      url = Addressable::URI.new(
        :scheme => "https",
        :host => "maps.googleapis.com",
        :path => "maps/api/directions/json",
        :query_values => {
          "origins" => origin,
          "destinations" => destination,
          "waypoints" => waypoints,
          "sensor" => false,
          # "key" => ENV["GOOGLE_KEY"],
          "units" => "imperial" 
        }
      ).to_s
    
      
      legs = JSON.parse(RestClient.get(url))["routes"].first["legs"]
    
      distance = 0
      legs.each do |leg|
        distance += leg["distance"]["text"][0..-4].split(",").join("").to_i unless leg["distance"]["text"][-2..-1] == "ft"
      end
    
      if events.length > 10
        "more than #{distance} miles."
      else
        "#{distance} miles"
      end
  end
  
  def notify_tour_create(tour)
    notify_members(tour.band.members,
      subject: tour,
      notification_type: :create)
  end
  
  def notify_tour_update(tour)
    notify_members(tour.band.members,
      subject: tour,
      notification_type: :update)
  end
  
  def notify_tour_destroy(tour)
    notify_members(tour.band.members,
      subject: tour,
      notification_type: :destroy)
  end
end

app/views/tours/_embed_code.html.erb
<% if tour %>
  <% url = map_embed_data_tour_url(tour) %>
<% else %>
  <% url = band_map_embed_data_url(@band) %>
<% end %>

&lt;meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' /&gt;
&lt;script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.js'&gt;&lt;/script&gt;
&lt;link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.css' rel='stylesheet' /&gt;
&lt;script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"&gt;&lt;/script&gt;

&lt;style&gt; #map { border: 1px solid black; width: 900px; height: 500px; } &lt;/style&gt;

&lt;div id='map'&gt;&lt;/div&gt;

&lt;script&gt;

	$.getJSON('<%= url %>', function(data) {
		var map = L.mapbox.map('map', 'examples.map-9ijuk24y')
		    	   .setView([38, -102.0], 9);

		map.scrollWheelZoom.disable();

		var featureLayer = L.mapbox.featureLayer().setGeoJSON(data);

		map.fitBounds(featureLayer.getBounds());
	
		featureLayer.addTo(map);
	});
	
&lt;/script&gt;

app/views/tours/_form.html.erb
<% heading = (@tour.persisted?) ? "Edit Tour" : "Create A Tour" %>
<% submit = (@tour.persisted?) ? "Update Tour" : "Create Tour" %>
<% action = (@tour.persisted?) ? tour_url(@tour) : band_tours_url(@band) %>

<h1><%= heading %></h1>
<hr>

<%= render 'layouts/errors' %>

<form id="new-tour-form" action="<%= action %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
	<% if @tour.persisted? %>
	  <input type="hidden" name="_method" value="put">
	<% end %>
	
	<div class="input">
	<label for="tour_name">Tour Name</label>
	<input id="tour_name" type="text" name="tour[name]" value="<%= @tour.name %>">
	</div>
	
	<h2> Add Shows </h2>
	
	<div class="checkboxes">
	<% @band.events.each do |event| %>
	    <div class="checkbox">
		<input type="checkbox" 
			   name="tour[event_ids][]" 
			   id="<%= event.object_id %>" 
			   value="<%= event.id %>"
			   <%= @tour.event_ids.include?(event.id) ? "checked" : "" %>>
	   		<label for="<%= event.object_id %>">
	   		  <%= l event.date, format: "%d %B %Y" %> -
	   		  <%= event.venue.name  %>
   		</label>
	   </div>
	   <hr>
    <% end %>
	</div>
	 
	<div class="submit"> 
	  <input type="submit" value="<%= submit %>">
	</div>
</form>

app/views/tours/_map.html.erb
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
<script src='https://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/v1.6.1/mapbox.css' rel='stylesheet' />

<div id='map'>
</div>

<style>
	#map-container {
		background: url("<%= asset_path('loader.gif') %>") no-repeat center;
		border: 1px solid black;
		width: 900px;
		height: 500px;
	}

	#map {
		width: 100%;
		height: 100%;
		z-index: 0;
	}
</style>

<script>
	var map = L.mapbox.map('map', 'examples.map-9ijuk24y')
	    	   .setView([38, -102.0], 9);

	map.scrollWheelZoom.disable();

	var featureLayer = L.mapbox.featureLayer()
	    .setGeoJSON(<%= geo_data %>)

	map.fitBounds(featureLayer.getBounds());
	
	featureLayer.addTo(map);

	var showCount = <%= JSON.parse(geo_data).count %>
</script>

app/views/tours/_tour.html.erb
<li id="tour-block">
	<ul class="block-header">
		<li class="block-header-item"> 
			<%= link_to tour.name, tour_url(tour) %>
		</li>
    </ul>
	
	<hr>
	
	<ul id="block-details">
		<li class="block-detail"> <%= pluralize(tour.events.count, 'show') %> </li>
		
		<% if current_user.is_band_admin?(tour.band) %>
			<li class="block-detail"> 
				<%= link_to 'delete', tour_url(tour), method: :delete %>
			</li>
		<% end %>
	</ul>
</li>

app/views/tours/edit.html.erb
<%= render 'form' %>

app/views/tours/new.html.erb
<% heading = (@tour.persisted?) ? "Edit Tour" : "Create A Tour" %>
<% submit = (@tour.persisted?) ? "Update Tour" : "Create Tour" %>
<% action = (@tour.persisted?) ? band_tour_url(@tour) : band_tours_url(@band) %>

<h2><%= heading %></h2>

<%= render 'layouts/errors' %>

<form id="new-tour-form" action="<%= action %>" method="post">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
	
	<label for="tour_name">Tour Name</label>
	<input id="tour_name" type="text" name="tour[name]" value="">
	
	<h2> Add Shows </h2>
	<% @band.events.each do |event| %>
	<div class="checkbox-field">
		<label for="<%= event.object_id %>">
		  <%= l event.date, format: "%d %B %Y" %>
		  <%= event.venue.name  %>
		</label>
		<input type="checkbox" 
			   name="tour[event_ids][]" 
			   id="<%= event.object_id %>" 
			   value="<%= event.id %>">
	</div>
    <% end %>
	 
	<input type="submit" value="<%= submit %>">
</form>

app/views/tours/show.html.erb
<h2> <%= link_to @tour.band.name, band_url(@tour.band) %> - <%= @tour.name %> <h2>
<h2> <%= @tour.events.count %> shows - 
	<%= link_to "Edit", edit_band_tour_url(@tour.band, @tour) %> |
	<%= link_to "Delete", tour_url(@tour), method: :delete %>
</h2>


<div id="map-container">
	<%= render 'tours/map', geo_data: @geo_data %>
</div>

<%= button_to "Get Embed", "javascript:dropDown('#hidden')", 
	method: :none, 
	class: "tour-buttons" %>
		
<%= button_to "Calculate Distance", "javascript:dropDown('#hidden-distance')", 
	method: :none, 
	class: "tour-buttons" %>
	
<%= button_to "Hide Shows", "javascript:dropDown('#hidden-shows')", 
	method: :none, 
	class: "tour-buttons",
		id: "show-reveal" %>
		
<%= button_to "Hide Map", "javascript:dropDown('#map-container')", 
	method: :none, 
	class: "tour-buttons",
		id: "map-reveal" %>

<div class="clearfixtop">
	<section id="swaparea">
		
		<div id="#hidden">
			<%= render 'events/embed' %>
		</div>
		
		<div id="hidden-distance">
			<h2> Total Travel Distance: 
				<%= image_tag "loader.gif", style: "display: inline; height: 30px" %>
			</h2>
		</div>
		
	</section>
</div>

<section id="hidden-shows" class="clearfixtop">
	<ul id="all-shows">
	   <%= render @tour.events, hide_band_name: true %>
	</ul>
</section>

<script>
	function dropDown(section) {
		$(section).animate({
			height: "toggle",
			opacity: "toggle"
		}, 500);
			
		if (section === "#hidden-distance") {
			$.ajax({
				url: "<%= distance_tour_url(@tour) %>",
				type: "GET",
				success: function (data) {
					$("#hidden-distance").find("h2").html("Total Travel Distance: " + data)
				}
			});
		};
		
		if (section === "#map-container" && $("#map-reveal").attr("value") === "Hide Map") {
			$("#map-reveal").attr("value", "Show Map")
		} else if (section === "#map-container") {
			$("#map-reveal").attr("value", "Hide Map")
		}
		
		if (section === "#hidden-shows" && $("#show-reveal").attr("value") === "Hide Shows") {
			$("#show-reveal").attr("value", "See  Shows")
		} else if (section === "#hidden-shows") {
			$("#show-reveal").attr("value", "Hide Shows")
		}
	};
	
	$("#all-shows").on("ajax:before", "form", function (event, data) {
		$('#map').css("display", "none");
	});
	
	$("#all-shows").on("ajax:success", "form", function (event, data) {
		var id = $(this).find("input[type=submit]").attr("id");
		$('#' + id).css("display", "none");
		$("#map-container").html(data)
	});
</script>