config/routes.rb
TourPlanner::Application.routes.draw do
  root to: 'users#show'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'facebook_login', to: 'sessions#facebook_login'
  get 'facebook_finalize', to: 'sessions#facebook_finalize'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update] do
    resources :member_requests, only: [:index]
    resources :notifications, only: [:index]
    put 'change_password', to: 'passwords#update'
  end
  
  resources :bands, only: [:create, :destroy, :show, :new, :index, :edit, :update] do
    resources :events, only: [:create, :destroy, :edit, :update, :new, :index]
    resources :tours, only: [:new, :create, :edit]
    resources :member_requests, only: [:create]
    post 'grab_shows', to: "events#grab_shows", as: "grab_shows"
    put 'grab_image', to: "bands#grab_image", as: "grab_image"
    get 'map_embed_data', to: "bands#map_embed_data"
  end
  
  put "member_requests/:id/deny_request", to: 'member_requests#deny', as: "deny_request"
  put "band_memberships/:id/make_admin", to: 'band_memberships#make_admin', as: "make_admin"
  
  post 'search', to: 'bands#search', as: 'band_search'
  
  resources :band_memberships, only: [:create, :destroy]
  
  resources :events, only: [:destroy, :index, :show]
  
  resources :venues, only: [:index, :show]
  
  resources :tours, only: [:show, :destroy, :update] do
    member do 
      get 'map_embed_data', to: "tours#map_embed_data"
      get 'distance', to: "tours#distance"
      put 'events/:event_id', to: "tours#remove_event", as: "remove_event"
    end
  end
  
  resources :notifications, only: [:destroy]
  
  namespace :demo do
    get 'one'
    get 'new_band'
    get 'band_page'
    get 'band_image'
    get 'shows_grabbed'
    get 'notifications'
    get 'admins'
    get 'band_tour'
  end
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  active             :boolean          default(TRUE)
#

class Band < ActiveRecord::Base
  default_scope where(active: true)
  
  attr_accessible :name, :image
  default_scope order('name')

  validates :name, presence: true
  
  has_attached_file :image, 
    styles: { medium: "500x500#", thumb: "200x200#" }, 
    default_url: "user_missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :events, dependent: :destroy, order: 'date ASC'
           
  has_many :tours, 
    through: :events, 
    source: :tour, 
    uniq: true
           
  has_many :band_memberships, dependent: :destroy
  
  has_many :members,
    through: :band_memberships,
    source: :member
    
  has_many :member_requests,
    class_name: 'MemberRequest',
    foreign_key: :band_id,
    dependent: :destroy 
    
  has_many :notifications, as: :notifiable
  
  include PgSearch
  pg_search_scope :search_by_name, against: :name
     
####

  def admins
    self.members.where("admin = true")
  end

  def make_member!(user)
    membership = self.band_memberships.new
    membership.member = user
    membership.save
  end
  
  def make_admin!(user)
    self.find_membership(user).toggle!(:admin)
  end 
    
  def role_of(user)
    self.band_memberships
      .where("member_id = ?", user.id)
      .try(:first).try(:role)
  end
  
  def find_membership(user) 
    BandMembership
      .where("member_id = ? AND band_id = ?", user.id, self.id)
      .first
  end
  
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  include BandsHelper
  include EventsHelper
  include NotificationsHelper

  before_filter :require_signed_in!, except: [:map_embed_data]
  
  def search 
    @search_criteria = params[:search]
    @bands = Band.search_by_name(@search_criteria)
  end
  
  def index
    @bands = Band.all
  end
  
  def show
    @band = Band
    .includes(:tours, :band_memberships, :events)
    .find(params[:id])
    
    @events = @band.events
    @tours = @band.tours
  end
  
  def new
    @band = Band.new
  end
  
  def create
    @band = Band.new(params[:band])
    
    begin 
      Band.transaction do
        @band.save!
        
        band_membership = @band.band_memberships.new(params[:band_membership]);
        band_membership.member = current_user
        band_membership.toggle(:admin)
        band_membership.save!
        
        flash[:success] = ["Your band has been let loose on the world!"]
        redirect_to band_url(@band)
      end
    rescue
      flash[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end 
  
  def edit
    @band = Band.find(params[:id])
  end
  
  def update
    @band = Band.find(params[:id])
    @band.assign_attributes(params[:band])
    
    changes = @band.changes
  
    if current_user.is_band_admin?(@band) && @band.save
      membership = @band.find_membership(current_user)
      membership.update_attributes(params[:band_membership])
      
      notify_band_update(@band, changes)
      
      if request.xhr?
        render text: band.image.url(:thumb)
      else
        flash[:success] = ["Band deets updated!"]
        redirect_to band_url(@band)
      end
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    band = Band.find(params[:id])
    
    notify_band_destroy(band)
    
    band.toggle!(:active)
    flash[:success] = ["Band was destroyed"]
    redirect_to current_user
  end
  
  def grab_image
    band = Band.find(params[:band_id])
    
    if grab_image_from_seat_geek?(band)
      flash[:success] = ["Image grabbed."]
      notify_band_image_grab(band)
      
      if request.xhr?
        render text: band.image.url(:thumb), status: 200
      else
        redirect_to band
      end
    else
      if request.xhr?
        render text: '/assets/user_missing.png' 
      else
        flash[:errors] = ["Couldn't find that image. Sorry."]
        redirect_to band
      end
    end
  end
  
  def map_embed_data
    allow_outside_access
    render json: 
      geo_data_events(
        Band.find(params[:band_id]).events, 
        up_to_date: true, 
        event_links: false, 
        ticket_links: true), 
        status: :ok
  end
end

app/helpers/bands_helper.rb
module BandsHelper
  include NotificationsHelper
  
  def grab_image_from_seat_geek?(band)
    url = seat_geek_band_url(band)
    performers = JSON.parse(RestClient.get(url))["performers"]
    
    begin 
      # try every sized image before giving up
      band.image = open(performers.first["image"]) || 
      open(performers.first["images"]["huge"]) ||
      open(performers.first["images"]["large"]) ||
      open(performers.first["images"]["medium"]) ||
      open(performers.first["images"]["small"])
      band.save!
      true
    rescue
      false
    end
  end
  
  def notify_band_update(band, changes)
    notify_members(band.members, 
      subject: band, 
      differences: changes,
      notification_type: :update)      
  end
  
  def notify_band_image_grab(band)
    notify_admins(band.admins, 
      subject: band, 
      notification_type: :image_change)
  end
  
  def notify_band_destroy(band)
     notify_members(band.members, 
       subject: band, 
       notification_type: :destroy)
  end
  
  private
  
  def seat_geek_band_url(band)
    band_name = band.name.downcase.split(" ").join("-")
    
    Addressable::URI.new(
      :scheme => "http",
      :host => "api.seatgeek.com",
      :path => "2/performers",
      :query_values => {
        "q" => band_name
      }
    ).to_s
  end
end

app/views/bands/_band.html.erb
<li id="band-block" class="clearfix">
	
	<a href="<%= band_url(band) %>">
		<%= image_tag band.image.url(:thumb), class: "band-list-image" %>
		
		<ul class="block-header">
		  <li class="block-header-item"> 
			   <%= band.name %>
		   </li>
		</ul>
	</a>

    <% if current_user.is_band_admin?(band) %>
		<%= link_to 'Edit Band', edit_band_url(band), class: "edit-link"%>
    <% end %>
	
</li>

app/views/bands/_band_heading.html.erb
<div id="show-heading" class="clearfix">
	<%= render 'layouts/errors' %>

	<div id="show-image">
	  <%= image_tag band.image.url(:thumb), class: "header-image", id: "band-show-image" %>
    </div>
	
	<h1> <%= band.name %> </h1>
	
    <% if current_user.is_band_admin?(band)%>
		<div id="change-image">
			<div class="edit">
			<% if current_user.is_band_admin?(band) %>
				<%= link_to 'Edit Band', edit_band_url(band)%> |
				<%= link_to 'Delete Band', band_url(band), method: :delete %> 
			<% end %>
			</div>
	
			<form id="edit-image"
				action="<%= band_url(band) %>" 
				method="post"   
				enctype="multipart/form-data">
			
				  <input type="hidden" name="_method" value="put">
	
				  <input type="hidden" 
						 name="authenticity_token" 
						 value="<%= form_authenticity_token %>">

				  <div class="input">
				    <label for="band_image">Change Band Image</label>
				    <input id="band_image" name="band[image]" type="file">
				  </div>
  
				  <div class="submit">
				    <input type="submit" value="Update Image">
				  </div>
			</form>
			or 
			<%= button_to "Grab Image", band_grab_image_url(band), method: :put, remote: true, id: "grab-image" %>
			<div id="grab-image-error"></div>
		</div>	
	<% end %>


	<h2> Members </h2>
	<ul id="members-list">
	
	    <% if !current_user.is_in_band?(band) && !current_user.has_requested_membership?(band) %>
	  	  <li class="member-list-item">
	  		 <%= button_to "Request Band Membership", band_member_requests_url(band) %> 
	  	  </li>
	    <% end %>

		<% band.band_memberships.each do |membership| %>

		  	<% if current_user.is_in_band?(band) && membership.member == current_user && %>
		  		<%= button_to "Leave Band", band_membership_url(current_user.find_membership(band)), method: :delete %>
		  	<% end %>
	
		  <li class="member-list-item">
			  <a href="<%= user_url(membership.member) %>">
			  <%= membership.member.email %> 
  
			  <% if membership.role %>
				  - <%= membership.role %>
			  <% end %>
  
			  <% if current_user.is_in_band?(band) %>
				  <%= membership.member.is_band_admin?(band) ? "(Admin)" : "" %>
			  <% end %>
			  </a>
  
			  <% if current_user.is_band_admin?(band) && !membership.member.is_band_admin?(band) %>
				  <%= button_to "Make Admin", make_admin_url(membership), method: :put %>
			  <% end %>
		  </li>
		<% end %>
	
	</ul>
</div>

<script>
$(document).ready(function () {
	
	var $grabForm = $($("#grab-image").closest("form"));

    $grabForm.on("ajax:before", function () {
    	$("#show-image").find("img").css("display", "none");
    });

	$grabForm.on("ajax:complete", function (event, data) {
		console.log(data.responseText);
		if (data.responseText === "/assets/user_missing.png") {
			$("#grab-image-error").html("Couldn't find that photo, sorry")
		}
		$("#band-show-image").attr("src", data.responseText);
		$("#show-image").find("img").css("display", "inline");
	});
	
})
</script>

app/views/bands/_event_dashboard.html.erb
<% if current_user.is_band_admin?(band) %>
	<%= button_to "Grab Shows From Seat Geek", band_grab_shows_url(band), id: "grab-shows" %>
<% end %>

<% unless band.events.empty? %>
	<a href="<%= band_events_url(band) %>">
		<div class="all-shows-box">
			<h2> All <%= band.name + "'s" %> Shows </h2>
		</div>
	</a>
<% end %>

<% if current_user.is_band_admin?(band) %>
	<a href="<%= new_band_event_url(band) %>">
		<div class="add-box">
			<h2> + Add Show </h2>
		</div>
	</a>	
<% end %>

app/views/bands/_form.html.erb
<% heading = (band.persisted?) ? "Edit #{band.name}" : "Create New Band" %>
<% submit = (band.persisted?) ? "Update Band" : "Create Band" %>
<% action = (band.persisted?) ? band_url(band) : bands_url %>

<h1> <%= heading %> </h1>
<hr>

<%= render "layouts/errors"%>

<form id="band-form" action="<%= action %>" method="post" enctype="multipart/form-data">
  <% if band.persisted? %>
    <input type="hidden" name="_method" value="put">
  <% end %>
	
  <input type="hidden" 
		 name="authenticity_token" 
		 value="<%= form_authenticity_token %>">
	
  <div class="input">		   
  <label for="band_name">Band Name</label>
  <input id="band_name"
   		 name="band[name]"
		 type="text"
		 value="<%= band.name %>">
  </div>

  <div class="file-input">		 
  <label for="band_image">Band Image</label>
  <input id="band_image" name="band[image]" type="file">
  </div>

  <div class="input">
  <label for="band_role">Your Role (optional)</label>
  <input id="band_role"
  		 name="band_memberships[role]"
		 type="text"
		 value="<%= band.role_of(current_user) %>">
  </div> 
  
  <div class="submit">
  <input type="submit" value="<%= submit %>">
  </div>
</form>

app/views/bands/_tour_dashboard.html.erb
<% if band.tours.count > 0 %>
	<h2> Tours (<%= band.tours.count %>) </h2>
	<ul id="all-tours">
	  <%= render band.tours %>
    </ul>
<% end %>

<% if current_user.is_band_admin?(band) && band.events.count > 0 %>
	<a href="<%= new_band_tour_url(band) %>">
		<div class="add-box">
			<h2> + Create a Tour </h2>
		</div>
	</a>
<% end %>

app/views/bands/edit.html.erb
<%= render 'bands/form', band: @band %>

app/views/bands/index.html.erb
<h1> All Bands </h1>

<ul id="all-bands">
	<%= render @bands %>
</ul>

app/views/bands/new.html.erb
<%= render 'form', band: @band %>

app/views/bands/search.html.erb
<h1> Bands Matching: "<%= @search_criteria %>" </h1>

<hr>

<ul id="all-bands">
  <%= render @bands %>
</ul>

app/views/bands/show.html.erb
<%= render 'band_heading', band: @band %>

<%= render 'event_dashboard', band: @band %>

<%= render 'tour_dashboard', band: @band %>