config/routes.rb
TourPlanner::Application.routes.draw do
  root to: 'users#show'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'facebook_login', to: 'sessions#facebook_login'
  get 'facebook_finalize', to: 'sessions#facebook_finalize'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, only: [:new, :create, :destroy, :show, :index, :edit, :update] do
    resources :member_requests, only: [:index]
    resources :notifications, only: [:index]
    put 'change_password', to: 'passwords#update'
  end
  
  resources :bands, only: [:create, :destroy, :show, :new, :index, :edit, :update] do
    resources :events, only: [:create, :destroy, :edit, :update, :new, :index]
    resources :tours, only: [:new, :create, :edit]
    resources :member_requests, only: [:create]
    post 'grab_shows', to: "events#grab_shows", as: "grab_shows"
    put 'grab_image', to: "bands#grab_image", as: "grab_image"
    get 'map_embed_data', to: "bands#map_embed_data"
  end
  
  put "member_requests/:id/deny_request", to: 'member_requests#deny', as: "deny_request"
  put "band_memberships/:id/make_admin", to: 'band_memberships#make_admin', as: "make_admin"
  
  post 'search', to: 'bands#search', as: 'band_search'
  
  resources :band_memberships, only: [:create, :destroy]
  
  resources :events, only: [:destroy, :index, :show]
  
  resources :venues, only: [:index, :show]
  
  resources :tours, only: [:show, :destroy, :update] do
    member do 
      get 'map_embed_data', to: "tours#map_embed_data"
      get 'distance', to: "tours#distance"
      put 'events/:event_id', to: "tours#remove_event", as: "remove_event"
    end
  end
  
  resources :notifications, only: [:destroy]
  
  namespace :demo do
    get 'one'
    get 'new_band'
    get 'band_page'
    get 'band_image'
    get 'shows_grabbed'
    get 'notifications'
    get 'admins'
    get 'band_tour'
  end
end

app/views/layouts/_errors.html.erb
<% if flash[:errors] && !flash[:errors].empty? %>
<section id="errors">
	<h3> Oops! Looks like something went wrong: </h3>
	<ul id="flash-list">
		<% flash[:errors].each do |error| %>
		  <li class="flash-list_item"> <%= error %> </li>
		<% end %>
	</ul>
</section>
<% end %>

app/views/layouts/_header.html.erb
<% if signed_in? %>

<header>
	<nav class="clearfix">
			
		<ul id="left-nav">
			<li class="nav-list-item"> 
				<%= link_to 'My Bands', user_url(current_user), id: 'manage-link' %> | 
			</li>
			
			<li class="nav-list-item"> 
			    <%= link_to 'All Bands', bands_url%> |
			</li>
			
			<li class="nav-list-item"> 
				<form action="<%= band_search_url %>" method="post">
					<input type="hidden" 
					name="authenticity_token" 
					value="<%= form_authenticity_token %>">
					
					<input id="header-search" type="search" name="search" placeholder="Search Bands">
				</form>
			</li>
			
		</ul>
		
		
		<ul id="right-nav">	
			<li class="nav-list-item"> 
				<%= link_to "Notifications", user_notifications_url(current_user) %> 
				( <%= current_user.pending_requests.count + current_user.notifications.count %> ) |
			</li>
			
			<li class="nav-list-item"> 
				<%= link_to "Settings", edit_user_url(current_user) %> |
			</li>
			
			<li class="nav-list-item"> 
				<%= button_to 'Log Out', logout_url, method: :delete, id: 'logout'  %>
			</li>
		</ul>
		
		
	</nav>
</header>

<% end %>

app/views/layouts/_successes.html.erb
<% if flash[:success] && !flash[:success].empty? %>
<section id="successes">
	<ul id="flash-list">
		<% flash[:success].each do |message| %>
		  <li class="flash-list_item"> <%= message %> </li>
		<% end %>
	</ul>
</section>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tour Planner</title>
  <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
	
<%= render 'layouts/header' %>

<div id="container" class="clearfix">
	<%= render 'layouts/successes' %>
	
	<%= yield %>
</div>

</body>
</html>